---
title: "&nbsp;"
output:
  html_document:
    toc_float: false
---


<style>
<!-- .button { -->
<!--     position: relative; -->
<!--     margin: 0px 0px 38px calc((100% - 980px) * 0.5); -->
<!--     left: 34px; -->
<!--     grid-area: 3 / 1 / 4 / 2; -->
<!--     justify-self: start; -->
<!--     align-self: start; -->
<!-- } -->
p     { display: table-row; text-align: center }
h2 { text-align:center}
.button { text-align:center}
a{padding: 10px}
.btn-default{background-color:#ec0c0c;
            border-color:#ec0c0c}
</style>

## For more information
## select an option below

```{r setup, include=FALSE}
##setting code chunks for rest ofz sections no code being shown, and no messages.
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE )
```

```{r libraries}
library(htmltools)
library(bsplus)
library(magrittr)
```


```{r}
br()
br()
div(class = "button",
    a(href="https://www.epfl.ch/labs/herus/index-html/projects/",
      target="_blank",
  bs_button(h3("Research Projects"))),

a(href="https://www.epfl.ch/labs/herus/index-html/team/",
  target="_blank",
  bs_button(h3("Our People")))
)
```